app = "sonanos-webapp"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[checks]
  [checks.health]
    type = "http"
    port = 3000
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    path = "/api/health"

[deploy]
  release_command = "npx prisma migrate deploy"

